### ISSUE TITLE
multi-gpus, first gpu no displays property. other gpu has displays.

### ISSUE THREAD

**Issue by BigSteel** [bencevans/screenshot-desktop#100]
![image](https://user-images.githubusercontent.com/5989219/48109726-8e40ba80-e283-11e8-9f6b-b14296aac128.png)

**Comment by bencevans** [comment]
@BigSteel were you able to fix the problem? Please could you provide `screenshot-desktop` version, operating system, outline gpu / display setup and maybe the code in use?

**Comment by BigSteel** [comment]
I mainly used the core code, because I needed to use it in the electron. In order to run normally after asar, special processing was carried out.
Usage scenario: get qrcode image information in a screen.
Windows 10 and macOS 10.14+ can run normally.

**Comment by BigSteel** [comment]
![image](https://user-images.githubusercontent.com/5989219/53465002-45f21600-3a87-11e9-9b63-abbd9d0d1111.png)
I have a new commit.
Bug fixed: Multiple displays of the same type can only capture one screen
