### ISSUE TITLE
Linux Image Magick is slow and probably not required

### ISSUE THREAD

**Issue by dcerisano** [bencevans/screenshot-desktop#11]
Image Magick's `import` is extremely slow, since it relies on the X11 client protocol.
**`scrot`** is included in apparently all Linux distros and accesses the system framebuffer directly.
This one line change to your lib/linux/index.js dramatically boosts performance:
  
**`exec('scrot desktop.jpg -e "cat desktop.jpg"', { ...`**
<br>
Notes
- `import`  briefly freezes (janks) all displays when executed
- Using the `crop` feature of  `import` further degrades its performance
- Using **`scrot`** with image processing packages like `sharp` (fast) or `jimp` (pure js) is optimal.
- Less than 5 fps achieved by `import`, with unacceptable jank
- Performance in excess of 60 fps achieved by **`scrot`**, with absolutely no jank

**Comment by dangilkerson** [comment]
@dcerisano What's your thoughts on https://github.com/naelstrof/maim instead of scrot?

**Comment by bencevans** [comment]
scrot certainly has the advantage that it's apparently available by default

**Comment by dcerisano** [comment]
I have not tested `maim` but it seems to be an extension of `scrot`, so performance should be similar unless they did something silly with X11.

I do like the feature that `main` can stream its output directly to stdout without saving to a file, allowing for command chain pipelining.

**Comment by dcerisano** [comment]
@dangilkerson I have not tested `maim` but it seems to be an extension of the `scrot` design. 
The performance should be similar as long as it reads directly from the frame buffer, like `scrot`.

One advantage then would be than `maim` allows for direct streaming of captured images to `stdout`, rather than forcing a file write. 
This allows for command chaining (pipelines) with utilities such as `jimp` and `sharp`. 
That would significantly improve integration performance over `scrot` with its mandatory file accesses.

**Comment by Blatoy** [comment]
I also have issues with imagemagick (screenshot is darker than it should be), I've tried with `scrot` and it's working well (except it's missing cropping)

Do you think it would be a good idea to have something like:
```js
function linuxSnapshot (options = {}) {
      [...]
      let commandLine = "";
      switch (options.linuxLibrary) {
        case "scrot": // Faster. Does not support crop.
          commandLine = `scrot "${filename}" -e -z "echo \\"${filename}\\""`;
          break;
        case "imagemagick":
        default:
          commandLine = `import -silent -window root -crop ${screen.crop} -screen ${filetype}:"${filename}" `;
          break;
      }
      [...]
}
```

and eventually crop manually using a canvas or something?

**Comment by dcerisano** [comment]
I use would ise `jimp` for for all image functions like crop. It is very fast.
Also note that using the crop function of `import` further degrades its performance.
