### ISSUE TITLE
Failed if path contains spaces

### ISSUE THREAD

**Issue by roman-dudin** [bencevans/screenshot-desktop#12]
Tested on Windows 8.1.
`Exception has occurred: Error`
`Error: Command failed: "****\node_modules\screenshot-desktop\lib\win32\screenCapture.bat" c:\path with spaces\screnshot.jpg`
`at ChildProcess.exithandler (child_process.js:275:12)`
`at emitTwo (events.js:126:13)`
`at ChildProcess.emit (events.js:214:7)`
`at maybeClose (internal/child_process.js:925:16)`
`at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)`

**Comment by roman-dudin** [comment]
Can be fixed by adding quotes to file path.

**Comment by bgschiller** [comment]
Fixed in #10

**Comment by roman-dudin** [comment]
It fails for me on Windows in /lib/win32/index.js

**Comment by bgschiller** [comment]
@roman-dudin I hear ya. #10 hasn't been merged yet, but when it is, it will begin to work. In the meantime, you can update your package.json to point at `bgschiller/screenshot-desktop#spaces-in-filenames` to get the updated code.

I don't have merge privileges on this repo ¯\_(ツ)_/¯

**Comment by roman-dudin** [comment]
@bgschiller I mean there are no changes in win32 folder at #10.

**Comment by bencevans** [comment]
Fixed in cc0ea398d7cc28a2c00a6f9c67d6f7aa9695381a. Published to npm in `screenshot-desktop@1.4.2`.
