### ISSUE TITLE
Mirrored displays in Mojave not working

### ISSUE THREAD

**Issue by delubyo** [bencevans/screenshot-desktop#129]
Using your lib is really helpful! Thanks for making this.
Found out something today, I connected another monitor and mirrored it instead of extending. 

Gives out this error:
{ Error: ENOENT: no such file or directory, open '/tmp/2019224-2558-8h7nfo.ca8ef.jpg'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/2019224-2558-8h7nfo.ca8ef.jpg' }

But works without problems if I extend and I get two screenshots. Have not tried it on lower MacOS.

**Comment by bencevans** [comment]
We use the screencapture utility on OSX. I don't have a MacBook I can play around on at the moment but would happily accept a pull request!

https://github.com/bencevans/screenshot-desktop/blob/master/lib/darwin/index.js
