### ISSUE TITLE
Blank screenshot when run from a windows background process

### ISSUE THREAD

**Issue by pro-mos** [bencevans/screenshot-desktop#134]
This package works if i run my code from cmd, but when i run my code from a process running in the background as a service the screenshot turns out black image.
When i tried to list the displays, it returned WinDisc as the only display, so i guess taking screenshots by a windows service is not possible?

**Comment by bencevans** [comment]
As I understand it this is due to Window's security profile services run under. There's some information and ways around it at https://docs.microsoft.com/en-us/windows/desktop/services/interactive-services.
