### ISSUE TITLE
Empty desktop on MacOS through ElectronJS

### ISSUE THREAD

**Issue by TonnyORG** [bencevans/screenshot-desktop#156]
**Describe the bug**
Calling this library from Electron ends up taking screenshots of the empty desktop: it pictures the wallpaper and the top bar, but none of the opened windows show up.

**To Reproduce**
```javascript
const screenshot = require('screenshot-desktop')
screenshot.listDisplays().then((displays) => {
      console.log(displays);
      screenshot({ screen: displays[displays.length - 1].id, filename: '/tmp/demo' + displays[displays.length - 1].id + '.png' })
        .then((img) => {
          console.log(img);
        });
    });
```

**Expected behavior**
Supposedly it should take a picture of the actual screen (with all the windows opened and so).

**Environment (please complete the following information):**
 - OS: MacOS Catalina 10.15
 - Engine: Electron
 - Version: 7.1.9

**Comment by bencevans** [comment]
That's odd, I wonder if it's some sort of security restiction. [Under the hood](https://github.com/bencevans/screenshot-desktop/blob/master/lib/darwin/index.js#L45-L62) we use the `screencapture` tool on OSX. Could you try running the following and see if you get the same result?

```
$ screencapture -x -t jpg out.jpg
```

**Comment by TonnyORG** [comment]
@bencevans I know what the problem is now, you have to enable "Screen Recording" for the app (your ide, your console, or wherever you run the screencapture from).

To fix it: System Preferences -> Securtity & Privacy -> Privacy (tab) -> Screen Recording -> and select the app(s) to allow it.

**Comment by bencevans** [comment]
Thanks for sharing!

**Comment by sankyn1** [comment]
I am too getting the only desktop in the below mac version if there is any open program it still only takes a screenshot  of the desktop in another mac version it is running perfectly I have allowed screen recording still it takes pictures of desktop only

<img width="581" alt="Screenshot 2021-02-05 at 3 07 36 PM" src="https://user-images.githubusercontent.com/14847098/107017026-a5551680-67c4-11eb-9d52-5761c29ad61f.png">

**Comment by bencevans** [comment]
@sankyn1 Might need to allow screen recording for a different process. Depending on how you're running it. E.g. If you're running your app from an IDE you may need to allow the IDE the screen recording permission.
