### ISSUE TITLE
Is it possible to capture part of screen?

### ISSUE THREAD

**Issue by ricardopolo** [bencevans/screenshot-desktop#157]
Is your feature request related to a problem? 
Is it possible to capture part of screen, giving some Coordinate or Specific Region (x1, y1, x2, y2)?

**Describe the solution you'd like**
Optional parameters to the capture method

**Additional context**
Look how robotjs works

**Comment by bencevans** [comment]
It's not currently possible, a lot of other desktop tools work by taking a full screenshot and then crop to region of interest. I can recommend [Jimp](https://github.com/oliver-moran/jimp#readme) for image manipulation in JS. I'd also welcome a pull request adding this functionality cross-platform.
