### ISSUE TITLE
Cannot take screenshot on vps window server!

### ISSUE THREAD

**Issue by zenlykoi** [bencevans/screenshot-desktop#158]
I'm building an website to control many vps window server.And i want to take screenshot on my vps.If i active in my vps,It still works normally.But opposite, I got a black image. What's my problem?Help me please(srr my english is not good !).

**Comment by bencevans** [comment]
Hi @zenlykoi. Please could you explain as to what you mean by opposite?

**Comment by zenlykoi** [comment]
> Hi @zenlykoi. Please could you explain as to what you mean by opposite?
This mean is, when i active (Remote Desktop) tab and take screenshot => i got a picture. But if i don't active this tab, such as i active my website in Chrome, and send a command to my vps to screenshot => i got a black picture!

**Comment by bencevans** [comment]
Are you sure you've opened this issue on the correct project? This project only runs using the node.js engine and not in the browser.

If you do have it running on a remote server, the node process may need to run under the desktop environment you're wishing to take an image of.

If I SSH into one of my Linux VPSs and run `scot`, one of the tools we use for linux to screenshot then I receive the following...

```
$ scrot
giblib error: Can't open X display. It *is* running, yeah?
```

For it to run properly I have set the DISPLAY environment variable with the following

```
$ DISPLAY=:0 scrot
```

I'm unsure as to how it works on Windows and OSX. What environment are you using?

**Comment by zenlykoi** [comment]
> Are you sure you've opened this issue on the correct project? This project only runs using the node.js engine and not in the browser.
> 
> If you do have it running on a remote server, the node process may need to run under the desktop environment you're wishing to take an image of.
> 
> If I SSH into one of my Linux VPSs and run `scot`, one of the tools we use for linux to screenshot then I receive the following...
> 
> ```
> $ scrot
> giblib error: Can't open X display. It *is* running, yeah?
> ```
> 
> For it to run properly I have set the DISPLAY environment variable with the following
> 
> ```
> $ DISPLAY=:0 scrot
> ```
> 
> I'm unsure as to how it works on Windows and OSX. What environment are you using?

I'm using window server 2012!

**Comment by bencevans** [comment]
Closing this issue as Windows Server falls out of the remit that this module attempts to support. However, if there are small changes required to fix issues relating to Windows Server I'd be happy to accept a pull request.
