### ISSUE TITLE
Multi windows screenshot feature

### ISSUE THREAD

**Issue by husin-sajjadi** [bencevans/screenshot-desktop#162]
Hi
Thank you for your great job.
In this library, Is there a feature for capturing from multi window desktop? (Mac, Windows and linux)

**Comment by bencevans** [comment]
Hi @husin-sajjadi. By this do you mean multiple monitors? If so then yes.

```js
screenshot.all().then((imgs) => {
  // imgs: an array of Buffers, one for each screen
})
```
