### ISSUE TITLE
 TypeError: Cannot read property 'crop' of undefined

### ISSUE THREAD

**Issue by rishabhrpg** [bencevans/screenshot-desktop#165]
I run 
```
const screenshot = require('screenshot-desktop')

screenshot().then((img) => {
  // img: Buffer filled with jpg goodness
  // ...
}).catch((err) => {
  // ...
})

```
node index.js 
(node:4150) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'crop' of undefined
    at listDisplays.then (/home/richardrishabh/Documents/tesserect/node_modules/screenshot-desktop/lib/linux/index.js:167:69)
(node:4150) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4150) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Engine [Node]
 - Version [10]

**Comment by bencevans** [comment]
I'm unable to reproduce your error. Could you check the output you're getting from `listDisplays()`? There may be an issue identifying your displays at https://github.com/bencevans/screenshot-desktop/blob/master/lib/linux/index.js#L151

```js
const screenshot = require('screenshot-desktop')

screenshot.listDisplays().then((displays) => {
  console.log(displays)
}).catch(console.error)
```

**Comment by kempoo** [comment]
> I'm unable to reproduce your error. Could you check the output you're getting from `listDisplays()`? There may be an issue identifying your displays at https://github.com/bencevans/screenshot-desktop/blob/master/lib/linux/index.js#L151
> 
> ```js
> const screenshot = require('screenshot-desktop')
> 
> screenshot.listDisplays().then((displays) => {
>   console.log(displays)
> }).catch(console.error)
> ```

I was able to reproduce on my raspberry Pi, indeed you were right, the problem lays in line 151 which filters the displays.
Result of `console.log(screens)` for headless pi connected with VNC:
`[ { width: 1280,
    height: 720,
    name: 'default',
    id: 'default',
    offsetX: 0,
    offsetY: 0,
    primary: false,
    crop: '1280x720+0+0' } ]
`
Solution proposal, change line 151 from :
`const screen = screens.find(options.screen ? screen => screen.id === options.screen : screen => screen.primary)`
to:
`const screen = screens.find(options.screen ? screen => screen.id === options.screen : screen => screen.primary || screen.id==="default" )`

**Comment by continue98** [comment]
@bencevans A similar bug can be obtained if you have 2 monitors. Are you planning to make fixes upstream?

**Comment by vegardsv** [comment]
I still get this error on version 1.12.7.  Has the fix beed reverted or can it be something else?

**Comment by bencevans** [comment]
It looks like this fix has been extended to add ` || screens[0]` to the end of the line but not sure this should break it. @vegardsv please could you share your output of `await screenshotDesktop.listDisplays()`?
