### ISSUE TITLE
Active windows in screenshots are missing.

### ISSUE THREAD

**Issue by hmake98** [bencevans/screenshot-desktop#168]
**Describe the bug**
Screenshot not contained any windows. It's just showing the title bar on the top.

**To Reproduce**
It's happening on the Mac os systems.

**Expected behavior**
The screenshot should contain the whole screen with windows in it.

**Screenshots**
![example](https://user-images.githubusercontent.com/23061515/89884359-11283f00-dbe7-11ea-83dd-0e16d2f52661.jpg)

**Environment (please complete the following information):**
 - OS: Mac Os Catalina
 - Engine Electron
 - Version 5.0.2

**Additional context**
It's not happening on every mac os system, but It's almost like Catalina systems are much more in ratio rather than other versions.

**Comment by bencevans** [comment]
Thanks for the report. This has popped up before and is due to changes in OSX security. You need to give the application Screen Recording permission. Please see https://github.com/bencevans/screenshot-desktop/issues/156#issuecomment-583008800 for guidance.
