### ISSUE TITLE
Windows 10 screenshot issue after installing in a electron application

### ISSUE THREAD

**Issue by sabarish1801** [bencevans/screenshot-desktop#172]
**Describe the bug**
In development environment it works fine but I got this error after installing My application which is packed by electron builder.

```
Error: Command failed: "C:\Program Files\MyApp\resources\app.asar.unpacked\node_modules\screenshot-desktop\lib\win32\screenCapture_1.3.2.bat" /list
    at ChildProcess.exithandler (child_process.js:304)
    at ChildProcess.emit (events.js:223)
    at maybeClose (internal/child_process.js:1021)
    at Socket.<anonymous> (internal/child_process.js:430)
    at Socket.emit (events.js:223)
    at Pipe.<anonymous> (net.js:664)
```

Note: It works only when I downgrade to 1.11.0
**To Reproduce**
1.Adding as a dependency in my electron app
2. Add this to package.json as mentioned in [this discussion](https://github.com/bencevans/screenshot-desktop/issues/135#issuecomment-685074823)
 ```
"asarUnpack": [
      "node_modules/screenshot-desktop/lib/win32"
    ]
```
3. Console throws the mentioned error on calling screenshot fn

**Expected behavior**
Screenshot to be taken

**Environment (please complete the following information):**
 - OS: Windows 10
 - Engine: Electron
 - Version : 9.1.0

Can you please look onto this?

**Comment by bencevans** [comment]
Thanks for your report. It looks like it's the same issue as #135, so shall close this in favour of the original with the further discussion around it. I've had a quick play but cannot dedicate much time to this issue currently. As stated before in #135 if someone is able to identify a better method in ensuring electron-builder doesn't mess with the path or a separate solution is found to run the bat from the electron-builder pack then a pull-request would be very welcome.
