### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by navneetgarggate6** [bencevans/screenshot-desktop#173]
**Describe the bug**
Uncaught (in promise) Error: Command failed: "node_modules\screenshot-desktop\lib\win32\screenCapture_1.3.2.bat" "E:\screenshot\shot.jpg" 
The system cannot find the path specified.

**To Reproduce**
"screenshot-desktop": "^1.12.2"
Installed on windows 10 with node v13.9.0

screenshot({ filename: 'shot.jpg' }).then((imgPath) => {
  console.log(imgPath)
  // imgPath: absolute path to screenshot
  // created in current working directory named shot.png
})

**Expected behavior**
Should create a file 

**Environment (please complete the following information):**
 - OS: Window 10
 - Engine Electron
 - 4.2.5

Operating System - Windows_NT(10.0.19041) - win32/x64
NodeJs - 13.9.0

Global packages
  NPM - 6.13.7
  yarn - 1.13.0
  @quasar/cli - 1.1.2
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.5 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.7 -- Quasar Framework App CLI
  @quasar/extras - 1.1.4 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - 4.2.5 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - 20.44.4 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.34.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

**Comment by bencevans** [comment]
Hi @navneetgarggate6, have you been through #172 and #135? This looks like the same issue to me, thus shall close this thread. Feel free to re-open if you believe it to be a separate issue with a note as to where it differs.

**Comment by navneetgarggate6** [comment]
I tested with the nodejs its working but for electron its not working. I tried the #152 changes but still no success.
