### ISSUE TITLE
Safari browser not supported

### ISSUE THREAD

**Issue by Epsilon-Rashmi** [bencevans/screenshot-desktop#181]
**Describe the bug**
The feature is not supported by **Safari Browser V13.1.2**

**To Reproduce**

**Expected behavior**

**Screenshots**
Error:
Currently unsupported platform. Pull requests welcome!
unSupported
downloadImg
downloadImg
invokeWithErrorHandling
invokeWithErrorHandling
(anonymous function)
downloadimg
downloadimg
invokeWithErrorHandling

**Environment (please complete the following information):**
 - OS: IOS
 - Engine [e.g. Node, Electron]
 - Version 10.13

**Comment by bencevans** [comment]
Hi @Epsilon-Rashmi I'm afraid I see taking screenshots from browser platforms to be out of scope for this module.
