### ISSUE TITLE
Comparison to Electron's desktop capturer?

### ISSUE THREAD

**Issue by andrewschreiber** [bencevans/screenshot-desktop#192]
Curious how this library compares to Electron's built in desktop capturer (https://www.electronjs.org/docs/api/desktop-capturer). Any performance or use case differences?

**Comment by bencevans** [comment]
Originally as I wasn't using electron but wanted this functionality from a node process. Not sure if Electron had these APIs when I first wrote either. A quick look, https://www.electronjs.org/docs/api/desktop-capturer is probably better for streaming whereas this is just individual screenshots. If you do benchmark though, please share!
