### ISSUE TITLE
network drive

### ISSUE THREAD

**Issue by perfectwebtech** [bencevans/screenshot-desktop#196]
hello

save on network drive

and  time tracking and keyword caputre any idea how i c an do that ?

**Comment by bencevans** [comment]
Take a look at libraries for Samba, FTP, NFS or whatever protocol your network drive speaks. Or if it's already mapped on your machine, use the path from Explorer/Finder. I'm afraid this isn't really the right place for the question though, you'll probably be able to get better support on IRC or similar programmer chat channels. This is for issues with the `screenshot-desktop` library.
