### ISSUE TITLE
scaled display in windows returns wrong width/height values

### ISSUE THREAD

**Issue by Chinafreak** [bencevans/screenshot-desktop#20]
When you're using MacBook's retina display and you run it on windows, then the resolution value is wrong from screenCapture_1.3.1.bat.

Retina Display is 2880x1800, .bat returns only  1646x1029

So that means the screenshot is cropped.

I've no experience how .bat files works, so I'm not sure if I can help. I'll try to fix it when I can do.
Anyways, there might be a solution for that:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/8a21ffbe-10ee-48be-8d01-1006b127c825/how-can-i-get-the-resolution-of-a-retina-monitor?forum=windowsgeneraldevelopmentissues

**Comment by bencevans** [comment]
Interesting, I haven't got a retina windows box to test on, a PR would be much appreciated.

**Comment by Chinafreak** [comment]
I think the batch use virtual resolution, but not native resolution. I didn't know this exsits either, too.

**Comment by Chinafreak** [comment]
Okay, I found it. It's not about retina display, it's about scaling from display settings. So we need dpi value to get correct width/height resolution.
@bencevans

![chrome_2018-03-14_13-22-29](https://user-images.githubusercontent.com/1526048/37402179-d7d448a6-278a-11e8-858f-5f95bd617e82.png)

**Comment by Pixelrobin** [comment]
One way to fix this on windows (latest version of 10) is to go to the actual location of the bat file after running it once (in node_modules), right click on the .exe it created, then go to `compatibility > Change high DPI settings -> Check "Override high DPI scaling behavior" -> set "Scaling performed by" to "Application"`.

Perhaps there is a way to set these settings in the .exe via nodejs itself?

**Comment by bencevans** [comment]
Best I've found is https://superuser.com/a/695024/197416

**Comment by Pixelrobin** [comment]
I can test it out when I get the time.

**Comment by Pixelrobin** [comment]
Ok, I tried the compatibility layer thing and it didn't seem to work :\

Just realized that the registry thing was a Windows 10 specific fix, something that works across all versions would be prefereable.

**Comment by NicolasNewman** [comment]
I'm experiencing the same issue as well. I have a 1920x1080 monitor but the returned image is 1536x864. Turning the scaling from 125% to 100% fixed the issue but I can't use that as a solution.

**Comment by NicolasNewman** [comment]
Disclaimer: I'm in the process of learning about Node and no nothing about C#

I looked in the .bat file that the Windows version uses and noticed the ScreenCapture class was used. After some quick googling, I found [this post](https://social.msdn.microsoft.com/Forums/windows/en-US/44c1fb89-3577-4f99-bcf6-d15d0efb7bb5/windows-form-screenprimaryscreenbounds-incorrect-for-1920x1080-screen-resolution?forum=winforms)

> It's a while since the last post but I have just experienced the same issue.
> 
> The issue seems to be related to whether the application is declared DPI Aware or not.
> 
> Mine was not, and so I had the outcome with the misreported screen working area.
> 
> Apparently, without DPI Awareness, Windows will scale the application according to it's own rules. And that seems to include what we might call the 'virtual' screen dimensions.
> With DPI Awareness, this does not happen.
> 
> So, how to make the application DPI Aware? The answer lies in including the following code in your application manifest file (app.manifest). You might have to click the 'Show all files' button in Solution Explorer to see the manifest file. Here's the code
> 
> <asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
>     <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
>       <dpiAware>true</dpiAware>
>     </asmv3:windowsSettings>
>   </asmv3:application>
> 
> Run the project with this in place and magically the screen dimensions will be reported as expected.

I don't know what exactly this entails but hopefully this is helpful and someone can make better sense of it then I can.

**Comment by NicolasNewman** [comment]
#86 I managed to fix the issue in this pull request.
