### ISSUE TITLE
Not working after build on ElectronJS

### ISSUE THREAD

**Issue by akanshSirohi** [bencevans/screenshot-desktop#201]
**Describe the bug**

**To Reproduce**
Build electron app contains the following code with electron-packager
const screenshot = require("screenshot-desktop");
screenshot({
      filename: `${app.getPath("desktop")}\\Screenshot.png`,
});
```
**Expected behavior**
Image file should be saved on desktop.

**Environment (please complete the following information):**
 - OS: Window 10
 - Engine: Electron
 - Version: 12.0.6

**Additional context**
It works fine during debugging

**Comment by bencevans** [comment]
Hi @akanshSirohi. Thanks for the report, we should get this written into the README but for the moment you'll want to take a read through https://github.com/bencevans/screenshot-desktop/issues/135.
