### ISSUE TITLE
needed screen id similar to electron id

### ISSUE THREAD

**Issue by vrprasanna97** [bencevans/screenshot-desktop#205]
Currently working on App in electron.js to take a screenshot. 
The Electron.js has its own screenshot features are known as desktopCapturer but in terms quality screenshot-desktop is way better.

Currently, we need to take a screenshot of e external monitor if the user clicks on the external monitor that particular screen should get captured.
 
so there is a need for id to be matched between screenshot-desktop and and electron js 

data of all display in electron:
![image](https://user-images.githubusercontent.com/67574673/119130902-72265280-ba56-11eb-82df-dd40b6dd5798.png)
data of all display in screenshot-desktop :
![image](https://user-images.githubusercontent.com/67574673/119131062-9f730080-ba56-11eb-94c0-89af0a134210.png)
 there is need of screen  id like electron js

**Comment by bencevans** [comment]
Are you able to get the true values of workArea, bounds and workAreaSize? Not ideal but you might be able to match these up with screenshot-desktops height, bottom, top, left, width, right. I'm not so sure how electron gets their ids. This PR might be of interest https://github.com/bencevans/screenshot-desktop/pull/193

**Comment by bencevans** [comment]
Closing as I'm don't believe this to be an issue with the library but shall leave unlocked as a useful discussion.

**Comment by vrprasanna97** [comment]
> Are you able to get the true values of workArea, bounds and workAreaSize? Not ideal but you might be able to match these up with screenshot-desktops height, bottom, top, left, width, right. I'm not so sure how electron gets their ids. This PR might be of interest https://github.com/bencevans/screenshot-desktop/pull/193

Thanks
