### ISSUE TITLE
While loop saving screenshots as jpeg, amounts exceed 500 and screenshot become not working

### ISSUE THREAD

**Issue by kennyli323** [bencevans/screenshot-desktop#21]
I am working to make a constant print screen function as computer vision on mac by using while loop in node.js. But every time the amount of screenshots exceed 500 something, the screenshot function stops and becomes disable so that the computer vision stops. Does anyone know about the reason and the solution behind?

**Comment by bencevans** [comment]
@kennyli323 please could you provide your code? Do you mean a while loop within this module or in your own code?

**Comment by kennyli323** [comment]
var msg = 'Job Automator'
var robot = require("robotjs");
const fs = require("fs");
//var screenshot = require('desktop-screenshot');
var screenshot = require('screenshot-desktop');
const cv = require('opencv');
//npm install peterbraden/node-opencv
var PythonShell = require('python-shell');
var http = require('http');
var sleep = require('sleep');
var express = require('express');
var APP = express();
var perfy = require('perfy');
const restart = require('make-it-restart')
 

var i = 0
var e

const testFolder = '/Users/kennyli/Documents/HELLO/screenshot/';

fs.readdirSync(testFolder).forEach(file => {

  if (parseInt(file.replace(".jpg","").substring(10)) > i)
  {
    i = file.replace(".jpg","").substring(10);
  }
  
})

i++;

  var x
  var y

  while (i > 0) {
      
    function sleep(time, callback) {
      var stop = new Date().getTime();
      while(new Date().getTime() < stop + time) {
          ;
      }
      callback();
   }

      //screenshot({ filename: 'screenshot.jpg' }).then((imgPath) => {
          // imgPath: absolute path to screenshot
          // created in current working directory named shot.png
        //});
      if (i > 10000) {
        i = 1;
        var exec = require('child_process').exec;
        var path = '/Users/kennyli/Documents/HELLO/screenshot/*';
  
        exec('rm -r ' + path, function (err, stdout, stderr) {
        // your callback goes here
        });
      }

        
    sleep(1000, function() {

    // executes after one second, and blocks the thread
      // handle or ignore error
      perfy.start('image');
      screenshot({ filename: '/Users/kennyli/Documents/HELLO/screenshot/screenshot' + i + '.jpg' }).then((imgPath) => {
        // imgPath: absolute path to screenshot
        e = perfy.end('image').time * 1000;
      }).catch((err) => {
        console.log("Screenshot failed", err);
       
    });
  })    

  
   // process.on('uncaughtException', function (err) {
     // console.log(err);
   // })
    
    process.on('uncaughtException', function(err){
       console.log(err);
       //Send some notification about the error  
    //    cmd = 'node vision.js';

    //  // Then I excute the command and kill the app if starting was successful
    //  var exec = require('child_process').exec;
    //  exec(cmd, function () {
    //    APP.logger('APPLICATION RESTARTED', 'success');
    //    process.exit(1);
    //  });
   
  
    });
   
    sleep(e + 100, function () {

    perfy.start('image');
    var img = '/Users/kennyli/Documents/HELLO/screenshot/screenshot' + i + '.jpg';
       cv.readImage(img, function (err, img) {
     if (err) {
     throw err;
    }
  
    const width = img.width();
    const height = img.height();
  
    img.save('/Users/kennyli/Documents/HELLO/screenshot/screenshot.jpg');

     //some code
     e = perfy.end('image').time * 1000;
    });
   });

    sleep(e + 1000, function() {
     
    var pathimage = '/Users/kennyli/Documents/HELLO/screenshot/screenshot' + i + '.jpg';
    if (fs.existsSync(pathimage)) {
      // Do something
      i++;
    }
    else
    {
      console.log(pathimage + ' does not exist.');
     
      let restartor = restart('node ./vision.js', { NODE_ENV: 'production' })
 
      restartor()
       
      setInterval(() => {
          restartor()
      }, 2000)
      // First I create an exec command which is executed before current process is killed
    //var cmds = 'node vision.js';
   
     // Then I excute the command and kill the app if starting was successful
     //var exec = require('child_process').exec;
    // exec(cmds, function () {
     //  APP.logger('APPLICATION RESTARTED', 'success');
      // process.exit(1);
     //});
   

    }
  });


  
}
  
  
    //PythonShell.run('crop.py', function (err) {
    //if (err) throw err;
    //console.log('finished');
    //});
  
// The path: crop.py to your python script
//var child_process = require('child_process');
  // runs the javascript output server side within nodejs

  
   // var img = '/Users/kennyli/Documents/HELLO/screenshot/screenshot.jpg';
     //   cv.readImage(img, function (err, img) {
    //  if (err) {
    //  throw err;
   // }
  
    //const width = img.width();
   // const height = img.height();
  
   //if (width < 1 || height < 1) {
  //    throw new Error('Image has no size');
  //  }
 // });
  
  //var result = findRemoveSync('/Users/kennyli/Documents/HELLO', {files: 'screenshot.png'})
      //sleep.sleep(10);
    //  var child_process = require('child_process');

    //  child_process.exec('deleteFile.py', function (err){
    //    if (err) {
    //    console.log("child processes failed with error code: " + err.code);
    //  }
   // });

  

 
  //var mouse = robot.getMousePos();
          
  //if (x != mouse.x && y != mouse.y)
  //{
 

  //console.log("Mouse is at x:" + mouse.x + " y:" + mouse.y);
  //x = mouse.x
  //y = mouse.y 
  
 // }
  //if (i = 9)
 // { i = 0 }

 // i++;
  
  
  
  
  var msg = 'Job Automator'
var robot = require("robotjs");
const fs = require("fs");
//var screenshot = require('desktop-screenshot');
var screenshot = require('screenshot-desktop');
const cv = require('opencv');
//npm install peterbraden/node-opencv
var PythonShell = require('python-shell');
var http = require('http');
var sleep = require('sleep');
var express = require('express');
var APP = express();
var perfy = require('perfy');
const restart = require('make-it-restart')
 

var i = 0
var e

const testFolder = '/Users/kennyli/Documents/HELLO/screenshot/';

fs.readdirSync(testFolder).forEach(file => {

  if (parseInt(file.replace(".jpg","").substring(10)) > i)
  {
    i = file.replace(".jpg","").substring(10);
  }
  
})

i++;

  var x
  var y

  while (i > 0) {
      
    function sleep(time, callback) {
      var stop = new Date().getTime();
      while(new Date().getTime() < stop + time) {
          ;
      }
      callback();
   }

      //screenshot({ filename: 'screenshot.jpg' }).then((imgPath) => {
          // imgPath: absolute path to screenshot
          // created in current working directory named shot.png
        //});
      if (i > 10000) {
        i = 1;
        var exec = require('child_process').exec;
        var path = '/Users/kennyli/Documents/HELLO/screenshot/*';
  
        exec('rm -r ' + path, function (err, stdout, stderr) {
        // your callback goes here
        });
      }

        
    sleep(1000, function() {

    // executes after one second, and blocks the thread
      // handle or ignore error
      perfy.start('image');
      screenshot({ filename: '/Users/kennyli/Documents/HELLO/screenshot/screenshot' + i + '.jpg' }).then((imgPath) => {
        // imgPath: absolute path to screenshot
        e = perfy.end('image').time * 1000;
      }).catch((err) => {
        console.log("Screenshot failed", err);
       
    });
  })    

  
   // process.on('uncaughtException', function (err) {
     // console.log(err);
   // })
    
    process.on('uncaughtException', function(err){
       console.log(err);
       //Send some notification about the error  
    //    cmd = 'node vision.js';

    //  // Then I excute the command and kill the app if starting was successful
    //  var exec = require('child_process').exec;
    //  exec(cmd, function () {
    //    APP.logger('APPLICATION RESTARTED', 'success');
    //    process.exit(1);
    //  });
   
  
    });
   
    sleep(e + 100, function () {

    perfy.start('image');
    var img = '/Users/kennyli/Documents/HELLO/screenshot/screenshot' + i + '.jpg';
       cv.readImage(img, function (err, img) {
     if (err) {
     throw err;
    }
  
    const width = img.width();
    const height = img.height();
  
    img.save('/Users/kennyli/Documents/HELLO/screenshot/screenshot.jpg');

     //some code
     e = perfy.end('image').time * 1000;
    });
   });

    sleep(e + 1000, function() {
     
    var pathimage = '/Users/kennyli/Documents/HELLO/screenshot/screenshot' + i + '.jpg';
    if (fs.existsSync(pathimage)) {
      // Do something
      i++;
    }
    else
    {
      console.log(pathimage + ' does not exist.');
     
      let restartor = restart('node ./vision.js', { NODE_ENV: 'production' })
 
      restartor()
       
      setInterval(() => {
          restartor()
      }, 2000)
      // First I create an exec command which is executed before current process is killed
    //var cmds = 'node vision.js';
   
     // Then I excute the command and kill the app if starting was successful
     //var exec = require('child_process').exec;
    // exec(cmds, function () {
     //  APP.logger('APPLICATION RESTARTED', 'success');
      // process.exit(1);
     //});
   

    }
  });


  
}
  
  
    //PythonShell.run('crop.py', function (err) {
    //if (err) throw err;
    //console.log('finished');
    //});
  
// The path: crop.py to your python script
//var child_process = require('child_process');
  // runs the javascript output server side within nodejs

  
   // var img = '/Users/kennyli/Documents/HELLO/screenshot/screenshot.jpg';
     //   cv.readImage(img, function (err, img) {
    //  if (err) {
    //  throw err;
   // }
  
    //const width = img.width();
   // const height = img.height();
  
   //if (width < 1 || height < 1) {
  //    throw new Error('Image has no size');
  //  }
 // });
  
  //var result = findRemoveSync('/Users/kennyli/Documents/HELLO', {files: 'screenshot.png'})
      //sleep.sleep(10);
    //  var child_process = require('child_process');

    //  child_process.exec('deleteFile.py', function (err){
    //    if (err) {
    //    console.log("child processes failed with error code: " + err.code);
    //  }
   // });

  

 
  //var mouse = robot.getMousePos();
          
  //if (x != mouse.x && y != mouse.y)
  //{
 

  //console.log("Mouse is at x:" + mouse.x + " y:" + mouse.y);
  //x = mouse.x
  //y = mouse.y 
  
 // }
  //if (i = 9)
 // { i = 0 }

 // i++;

**Comment by kennyli323** [comment]
yes, I tried to restart the program but that doesn't seem to work.

**Comment by kennyli323** [comment]
var msg = 'Job Automator'
var robot = require("robotjs");
const fs = require("fs");
//var screenshot = require('desktop-screenshot');
var screenshot = require('screenshot-desktop');
const cv = require('opencv');
//npm install peterbraden/node-opencv
var PythonShell = require('python-shell');
var http = require('http');
var sleep = require('sleep');
var express = require('express');
var APP = express();
var perfy = require('perfy');
const restart = require('make-it-restart')
 

var i = 0
var e

const testFolder = '/Users/kennyli/Documents/HELLO/screenshot/';

fs.readdirSync(testFolder).forEach(file => {

  if (parseInt(file.replace(".jpg","").substring(10)) > i)
  {
    i = file.replace(".jpg","").substring(10);
  }
  
})

i++;

  var x
  var y

  while (i > 0) {
      
    function sleep(time, callback) {
      var stop = new Date().getTime();
      while(new Date().getTime() < stop + time) {
          ;
      }
      callback();
   }

      //screenshot({ filename: 'screenshot.jpg' }).then((imgPath) => {
          // imgPath: absolute path to screenshot
          // created in current working directory named shot.png
        //});
      if (i > 10000) {
        i = 1;
        var exec = require('child_process').exec;
        var path = '/Users/kennyli/Documents/HELLO/screenshot/*';
  
        exec('rm -r ' + path, function (err, stdout, stderr) {
        // your callback goes here
        });
      }

        
    sleep(1000, function() {

    // executes after one second, and blocks the thread
      // handle or ignore error
      perfy.start('image');
      screenshot({ filename: '/Users/kennyli/Documents/HELLO/screenshot/screenshot' + i + '.jpg' }).then((imgPath) => {
        // imgPath: absolute path to screenshot
        e = perfy.end('image').time * 1000;
      }).catch((err) => {
        console.log("Screenshot failed", err);
       
    });
  })    

  
    process.on('uncaughtException', function(err){
       console.log(err);
  
    });
   
    sleep(e + 100, function () {

    perfy.start('image');
    var img = '/Users/kennyli/Documents/HELLO/screenshot/screenshot' + i + '.jpg';
       cv.readImage(img, function (err, img) {
     if (err) {
     throw err;
    }
  
    const width = img.width();
    const height = img.height();
  
    img.save('/Users/kennyli/Documents/HELLO/screenshot/screenshot.jpg');

     //some code
     e = perfy.end('image').time * 1000;
    });
   });

    sleep(e + 1000, function() {
     
    var pathimage = '/Users/kennyli/Documents/HELLO/screenshot/screenshot' + i + '.jpg';
    if (fs.existsSync(pathimage)) {
      // Do something
      i++;
    }
    else
    {
      console.log(pathimage + ' does not exist.');
     
      let restartor = restart('node ./vision.js', { NODE_ENV: 'production' })
 
      restartor()
       
      setInterval(() => {
          restartor()
      }, 2000)


    }
  });


  
}

**Comment by bencevans** [comment]
It looks like you're using the module correctly. If you replicate the issue with a small test script then please do share that with us as we can make it into a test.

If the code you shared is the `vision.js` file, it appears that you're starting it every 2 seconds and then each process spawned is doing the same again. I think this is the issue you're facing and not related to the functionality of this module.

**Comment by kennyli323** [comment]
var msg = 'Job Automator'
const fs = require("fs");
//var screenshot = require('desktop-screenshot');
var screenshot = require('screenshot-desktop')
var perfy = require('perfy');

 

var i = 0
var e

const testFolder = '/Users/kennyli/Documents/HELLO/screenshot/';

fs.readdirSync(testFolder).forEach(file => {

  if (parseInt(file.replace(".jpg","").substring(10)) > i)
  {
    i = file.replace(".jpg","").substring(10);
  }
  
})

i++;

  while (i > 0) {
      
    function sleep(time, callback) {
      var stop = new Date().getTime();
      while(new Date().getTime() < stop + time) {
          ;
      }
      callback();
   }


        
    sleep(1000, function() {

    // executes after one second, and blocks the thread
      // handle or ignore error
      perfy.start('image');
      screenshot({ filename: '/Users/kennyli/Documents/HELLO/screenshot/screenshot' + i + '.jpg' }).then((imgPath) => {
        // imgPath: absolute path to screenshot
        e = perfy.end('image').time * 1000;
      }).catch((err) => {
        console.log("Screenshot failed", err);
       
    });
  })   
   
   i++;
  }

**Comment by kennyli323** [comment]
It's much simpler. I have tested it. The screenshot files accumulated to 523 and stopped without error caught by the program.

**Comment by bencevans** [comment]
I wouldn't expect it to error as it's successfully taking the screenshots. It is due to the loop in your code that it's taking so many.

If you run the following, only one image should be generated (snap.jpg).

```js
var screenshot = require('screenshot-desktop');

screenshot({ filename: 'snap.jpg' })
    .then(console.log)
    .catch(console.error)
```

If you're looking to take a screenshot every 1 second, the following works for me...

```js
const screenshot = require('screenshot-desktop');

setInterval(() => {

    const name = (new Date()).toISOString() + '.jpg'

    screenshot({ filename: name })
        .then(() => {
            console.log('written ' + nm)
        })
        .catch(console.error)

}, 1000)
```

Console Output:

```
$ node index.js 
written 2018-03-16T16:45:59.651Z.jpg
written 2018-03-16T16:46:00.656Z.jpg
written 2018-03-16T16:46:01.658Z.jpg
^C
```

**Comment by kennyli323** [comment]
Thanks, setInterval works like a charm.
