### ISSUE TITLE
Unsupported Platform (mac)

### ISSUE THREAD

**Issue by Stephanehk** [bencevans/screenshot-desktop#211]
I am attempting to run the following example (from this repo) and I get the error below telling me my platform is unsupported. I am using macOS Catilina 10.15.7, which I thought was supposed to be supported by this. 

Code:
```
screenshot().then((img) => {
          // img: Buffer filled with jpg goodness
          fs.writeFile('out.jpg', img, function (err) {
            if (err) {
              throw err
            }
            console.log('written to out.jpg')
          })
          // ...
        }).catch((err) => {
          console.log(err);
 })
```

Error:
```
Error: Currently unsupported platform. Pull requests welcome!
    at unSupported (index.js:11)
    at TrajHandler.update (trajHandler.js:921)
    at Game.update (game.js:69)
    at gameLoop (index.js:184)
```

**Comment by bencevans** [comment]
Hmm, odd. I'm on macOS Big Sur on this machine, and it hasn't been an issue. Please could your run the following in Terminal and send back the output?

```
$ node -e "console.log(process.platform)"
```

**Comment by bencevans** [comment]
Oh, are you using Electron and trying to run in the Window without nodeInterop enabled maybe?

**Comment by bencevans** [comment]
Closing as unable to replicate, haven't heard of this being an issue for others and no follow up to prior questions.
