### ISSUE TITLE
Error ENOTDIR on Mac os in electron App

### ISSUE THREAD

**Issue by pityulin** [bencevans/screenshot-desktop#213]
Error: spawn ENOTDIR\n    at ChildProcess.spawn (internal/child_process.js:407:11)\n    at spawn (child_process.js:557:9)\n    at Object.execFile (child_process.js:241:17)\n    at Object.t.<computed> [as execFile] (electron/js2c/asar_bundle.js:5:2208)\n    at exec (child_process.js:162:25)\n    at electron/js2c/asar_bundle.js:5:12008\n    at /Contents/Resources/app.asar/node_modules/screenshot-desktop/lib/darwin/index.js:200:9\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"

the error occurs when the method is called screenshot.all()

Darwin 20.5.0 Darwin Kernel Version 20.5.0
npm --version 7.20.0
node --version v16.2.0

error in \screenshot-desktop\lib\darwin\index.js
201:     cwd: __dirname

the  similar bug is fixed for windows https://github.com/bencevans/screenshot-desktop/commit/68eee48

**Comment by bencevans** [comment]
I'm not quite sure this is the same as the referenced fix for windows as the call in the windows file is to a local script/program, whereas on macOS, we call a program that should be in the PATH anyway. I wonder if it's more down to where you're running the script from. The path you initially state looks like a windows path but running on Darwin/macOS O.o

**Comment by bencevans** [comment]
Ah, it's to do with `__dirname`. Does electron overwrite this with something, maybe at build time and becomes static? 🤔

**Comment by pityulin** [comment]
for mac os there is no need to set the current folder. 
when __dirname is called, the folder is defined as app.asar and not app.asar.unpacked (screenshot-desktop module added to unpack)

**Comment by bencevans** [comment]
Aha. Fancy sending a pull request?

**Comment by pityulin** [comment]
Added
