### ISSUE TITLE
Command Failed: import -silent -window root -crop 1600x900+0+0 -screen jpeg

### ISSUE THREAD

**Issue by r-shafi** [bencevans/screenshot-desktop#218]
Error in Ubuntu 21.04 in an Electron app.
![Error Screenshot](https://i.ibb.co/0jCrtCk/Screenshot-from-2021-09-12-21-01-58.png)

**Comment by bencevans** [comment]
This looks like ImageMagick isn't installed on the machine which provides the import command, could you try running `sudo apt-get install imagemagick` to see if it resolves the error?
