### ISSUE TITLE
Currently unsupported platform

### ISSUE THREAD

**Issue by sakurahe** [bencevans/screenshot-desktop#235]
Run in the browser and receive an error: Currently unsupported platform

<img width="521" alt="image" src="https://user-images.githubusercontent.com/29187945/164583943-1602db2c-8463-4812-9382-688733a4d87d.png">

**Comment by bencevans** [comment]
Thank you for your report, this is however expected behaviour and have no plans to support the browser environment. This module supports the nodejs/electron runtimes for Mac Linux and Windows.
