### ISSUE TITLE
get  scrrenshot in  linux

### ISSUE THREAD

**Issue by samantrader** [bencevans/screenshot-desktop#244]
i  have  this  code   in  ubuntu    

const screenshot = require('screenshot-desktop');
            screenshot( {   linuxLibrary : 'imagemagick'}).then((img) => {
             
                console.log(img)                         
            })

but    when  run     make  error  :

(node:5024) UnhandledPromiseRejectionWarning: Error: Command failed: import -silent -window root -crop 1024x768+0+0 -screen jpeg:"hosi"
import-im6.q16: unable to read X window image `root': Resource temporarily unavailable @ error/xwindow.c/XImportImage/4977.
import-im6.q16: missing an image filename `jpeg:hosi' @ error/import.c/ImportImageCommand/1276.

**Comment by bencevans** [comment]
I've just replicated it here. This is due to running Ubuntu using Wayland rather than X. We've got a ticket (#220) open to track Wayland support and any pull request would be welcome.
