### ISSUE TITLE
Doesn't work in Ubuntu OS 22.04

### ISSUE THREAD

**Issue by vanovarderesyan** [bencevans/screenshot-desktop#248]
I think the screenshot functionality has changed on the OS, that is why I am facing such an issue. What can you suggest here?

**Comment by bencevans** [comment]
Please provide more information such as following the issue template. Screenshots/errors would be useful. I suspect you're running Wayland rather than X. Please take a look at #220. Feel free to reopen if that doesn't relate/more information is provided.

**Comment by vanovarderesyan** [comment]
> Please provide more information such as following the issue template. Screenshots/errors would be useful. I suspect you're running Wayland rather than X. Please take a look at #220. Feel free to reopen if that doesn't relate/more information is provided.

![image](https://user-images.githubusercontent.com/36670993/192466130-fe4b79aa-ae55-49aa-86c1-daccea3f4d1f.png)
![image](https://user-images.githubusercontent.com/36670993/192466978-39c5cdef-b770-4ba8-adf6-1430071a9f85.png)

https://askubuntu.com/questions/1407494/screen-share-not-working-in-ubuntu-22-04-in-all-platforms-zoom-teams-google-m

In the 1st screenshot, you can see the issue on Ubuntu 22.04, I tried to screenshot manually due to what you are using. In the 2nd screenshot, I show "Wayland rather than X", which I changed to "X" via my provided link. I guess the best option is to run your module on Ubuntu 22.04 model and get sure. Now I am trying again, If there will be any possible variant will let you know.
