### ISSUE TITLE
Windows and PM2 support

### ISSUE THREAD

**Issue by markosole** [bencevans/screenshot-desktop#251]
**Describe the bug**
I am running Node 16 and app that is running with PM2. Problem is that it can't grab screenshot when app is started with PM2. I am trying to run it as a windows service and have tried node-windows as well. Everything works fine when I run it as node myApp.js.

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Windows 10/11
 - Engine: Node
 - Version 16

Have anyone experienced anything like that and managed to find solution?

NOTE: When used with forever module like:  ``forever start app.js``  then works fine.

**Comment by bencevans** [comment]
We've researched into this a bit previously, thread at https://github.com/bencevans/screenshot-desktop/issues/185. It's due to the limitations placed by Windows when a process runs as a Service. If you can find a solution, it would be great to share it on #185.
