### ISSUE TITLE
Does not write files with ":"

### ISSUE THREAD

**Issue by chris-rudmin** [bencevans/screenshot-desktop#30]
I noticed when trying to save a screenshot with `:` in the filename, the file is not written, but no error is thrown. My use-case is I am writing images with a timestamp generated with `date.toISOString()` which will include a `:`.

Environment: Win 8, x64
To reproduce:
`screenshot({ filename: 'a:b.jpg' });`

**Comment by bencevans** [comment]
It would appear that Windows doesn't support colons in a filename according to https://stackoverflow.com/a/10386576/705977

**Comment by chris-rudmin** [comment]
@bencevans Thanks, I wasn't aware of that limitation. I would still expect `screenshot()` to throw an error if the file cannot be written for whatever reason.
