### ISSUE TITLE
Increase maxBuffer

### ISSUE THREAD

**Issue by MiniGod** [bencevans/screenshot-desktop#4]
The `maxBuffer` option is set to `1024 * 1000`, but for me it is not enough, and I get the following error: `Error: stdout maxBuffer exceeded.`

I'm running a multi-monitor setup on linux with a total resolution of 3840 x 2160.

Doubling the `maxBuffer` works for me.

Is `1024 * 1000` a random number that worked for you or does it have some meaning?

**Comment by bencevans** [comment]
`maxBuffer` was indeed set to a "just works" value. Ideally we need to calculate what it should be.

**Comment by bencevans** [comment]
Added in #7. Released in `v1.3.0`.
