### ISSUE TITLE
Aplication fails to compile on Linux with "ERROR in ./~/screenshot-desktop/lib/win32/index.js"

### ISSUE THREAD

**Issue by ivanlucky22** [bencevans/screenshot-desktop#80]
Hi!
Thanks for interesting application but I'm facing an issue.

After running `apt-get install imagemagick` and  `npm install --save screenshot-desktop` on my Lubuntu application fails to compile with 
```
ERROR in ./~/screenshot-desktop/lib/win32/index.js
[0] Module not found: Error: Can't resolve 'child_process' in '......../node_modules/screenshot-desktop/lib/win32'
```
Version of screenshot-desktop is 1.5.0
Could you please help with that?

**Comment by bencevans** [comment]
Are you attempting to use this module in a browser by chance? This module should be executed using node.js.
