### ISSUE TITLE
This module is not working inside electron asar archive

### ISSUE THREAD

**Issue by radar155** [bencevans/screenshot-desktop#98]
Because of [this](https://electronjs.org/docs/tutorial/application-packaging#executing-binaries-inside-asar-archive) limitation of asar archives, this module isn't working in Windows compiled electron apps.
I already found a workaround.

Inside  lib/win32/index.js, instead of
` exec('"' + path.join(__dirname, 'screenCapture_1.3.2.bat') + '" "' + imgPath + '" ' + displayChoice, {
      cwd: __dirname
    }
...`

you can
` exec('"' + path.join(__dirname.replace('app.asar', 'app.asar.unpacked'), 'screenCapture_1.3.2.bat') + '" "' + imgPath + '" ' + displayChoice, {
      cwd: __dirname.replace('app.asar', 'app.asar.unpacked')
    }
...`

And you can do the same for the listDisplays() method.

The point is if make sense doing this fix in this module, maybe not.
[This](https://github.com/epsitec-sa/hazardous) library could be helpful as workaround too. It basically rewrite _path.join_ method and replace 'app.asar' with 'app.asar.unpacked' if in path. But anyway, in this module you are passing ___dirname_ directly as _cwd_ parameter and so things can't works.

More infos [here](https://github.com/electron/electron/issues/8476)

**Comment by nicomac** [comment]
Can confirm. Please update the source with the fix presented above. Thanks!

**Comment by bencevans** [comment]
Open a pull-request and I'm happy to get it pushed up. I'm not using electron personaly but happy for support to be added.

**Comment by radar155** [comment]
[Here](https://github.com/bencevans/screenshot-desktop/pull/120) is the pull request. As I said, this solution is not the best, but it just works.

**Comment by bencevans** [comment]
Thanks @radar155. Have merged your pull-request and published to npm in [`v1.5.5`](https://github.com/bencevans/screenshot-desktop/releases/tag/v1.5.5).

**Comment by mistryhiren94** [comment]
same issue,
this module isn't working in MAC compiled electron apps

**Comment by radar155** [comment]
You can investigate/fix the problem by reading my first post and editing the `lib/darwin/index.js` file. My PR fixed the problem just for Windows as I said. Unfortunately I can't test in mac os enviorment but by reading the source code, the problem should be specular to that on windows. I'm busy in this period but I could send a more elegant and general solution in few weeks.

**Comment by mistryhiren94** [comment]
@radar155 thanks

**Comment by mistryhiren94** [comment]
@radar155 thanks,
that worked,
i just update `lib/darwin/index.js` this file
cwd: __dirname
to
cwd: __dirname.replace('app.asar', 'app.asar.unpacked')

and it worked,
thanks for your help :)
